version: '3'

services:
  puem_test_service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ipuserver_internal
    working_dir: /app
    command: python run.py
    ports: # external:internal
      - "8000:80"
    volumes:
      - ./static:/app/static
      - ./.env:/app/.env
    # env_file:
    #   - .env
    environment:
      - INTERNAL_PORT=80
    labels:
      - sablier.enable=true
      - sablier.group=ipuserver

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - puem_test_service
    networks:
      - ipuserver_internal
    labels:
      - sablier.enable=true
      - sablier.group=ipuserver

networks:
  ipuserver_internal:
    external: true